name: Code Freeze
on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: Code Freeze
    runs-on: ubuntu-24.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - name: Fail if Code Freeze is enabled
      run: |
        exit 0
